### ISSUE TITLE
cloud IDE not working for me

### ISSUE THREAD

**Issue by jspanjaard** [alis-x/docs#1]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/28752468/160921028-34349a3b-af91-4db9-85c6-9c452bc2c13e.png">

**Comment by kyle-alis** [comment]
Looking into it. Believe it is to do with the gitpod entering an idle state. Will respond with an update asap.

**Comment by kyle-alis** [comment]
Made an update to the link. Believe the issue is resolved. Please let us know if it does persist.

**Comment by jspanjaard** [comment]
Still struggling
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28752468/160953280-35872473-2a92-4cfe-a06a-15d90a4811ef.png">

**Comment by jspanjaard** [comment]
There is something strange happening when I run go mod tidy
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28752468/161037434-c4526cf6-c79b-4db3-94ef-7cc244a343ef.png">

**Comment by jspanjaard** [comment]
do I need to run go mod tidy?

**Comment by kyle-alis** [comment]
@jspanjaard, We are currently still setting up the environment for the cloud IDE. It is not production ready yet. Will let you know as soon as it is ready to play in.

**Comment by jspanjaard** [comment]
Great. Will stop testing until you give the go-ahead.
